---
site_name: "LAB-11138 - Intelligent Interactions: Elevating Retail and Healthcare with Webex Calling AI" # This must begin with the session ID, e.g. LABXXX-1234 This is my Cisco Live Lab
site_description: "LAB-11138 - Intelligent Interactions: Elevating Retail and Healthcare with Webex Calling AI" # must be same as "site_name"
site_author: RAJAMANI Nallakaruppan
copyright: Copyright &copy; 2026 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
  repo: "https://github.com/WebexCC-SA/LAB-11138s.git"
  site_event: test
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
plugins:
  - search
  - macros
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/wx1Splash_new.gif
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - About the Lab: "welcome.md"
  - "Lab Topology and Scenario": "lab-topology-and-scenario.md"
  - "Accessing the lab": "accessing-the-lab.md"
  - "Healthcare":
      - "Healthcare": "healthcare.md"
      - "Licensing users for Customer Assist": "licensing-users.md"
      - "Create Appointment/ Billing queue": "create-appointment-billing-queue.md"
      - "Enabling Call Recording for Appointment Billing queue": "call-recording.md"
      - "Adding Supervisor to Appointment Billing queue": "adding-supervisor.md"
      - "Wrap up reason": "wrap-up-reason.md"
      - "Create Nurse queue": "create-nurse-queue.md"
      - "AI Receptionist": "ai-receptionist.md"
      - "Enabling AI Features in Webex Calling": "enabling-ai-features.md"
      - "Testing and Verification": "testing-and-verification.md"
      - "Access Customer assist queue recordings": "queue-recordings.md"
      - "Webex Calling Customer Assist Analytics and Reporting": "analytics-and-reporting.md"
  - Lab:
      - Overview: overview.md
      - Lab 1 - Getting Started: lab1_getting_started.md
      - Conclusion: conclusion.md
  - Topologies: topologies.md
  - How to use this guide:
      - Setting up and using the tool:
        - Initial Setup: howToUse/initialSetup.md
        - Using the tool after the initial setup: howToUse/postInitial.md
        - Publishing your changes: howToUse/syncChanges.md
      - Useful Tools and Resources: howToUse/usefulTools.md
      - Importing from Word (docx): howToUse/importingFromWord.md
      - Styling and Advanced Features:
        - Custom Features: howToUse/customFeatures.md
        - Custom Admonitions: howToUse/admonition.md
      - Looking for Inspiration: howToUse/previousEventLabs.md
      - Before the Event: howToUse/beforeTheEvent.md